import { readFileSync } from 'fs'; import crypto from 'crypto'; import puppeteer from 'puppeteer';
const raw=readFileSync('.env.local','utf8');
const secret=(raw.match(/ADMIN_TOKEN_SECRET\s*=\s*"?([^"\n]+)"?/)||[])[1];
const pl={id:'admin-local-check',email:'l@w.cz',name:'Local Check',role:'owner',exp:Date.now()+3600_000};
const e=Buffer.from(JSON.stringify(pl)).toString('base64url');
const token=`${e}.${crypto.createHmac('sha256',secret).update(e).digest('base64url')}`;
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const b=await puppeteer.launch({headless:'new'});
const p=await b.newPage(); await p.setUserAgent(UA); await p.setViewport({width:1440,height:900});
await b.setCookie({name:'admin-session',value:token,domain:'localhost',path:'/'});
await p.goto('http://localhost:3000/admin/audity',{waitUntil:'networkidle0',timeout:90000});
await new Promise(r=>setTimeout(r,2000));
const vis=await p.evaluate(()=>{const c=document.querySelector('.site-chrome');return c?getComputedStyle(c).display:'není';});
console.log('site-chrome na adminu:', vis, '(má být none)');
await p.screenshot({path:'/tmp/audity2.png'});
const p2=await b.newPage(); await p2.setUserAgent(UA);
await p2.goto('http://localhost:3000/sluzby',{waitUntil:'networkidle0'});
console.log('hlavičky na /sluzby:', await p2.evaluate(()=>document.querySelectorAll('header').length));
await b.close();
