import { C } from '../../lib/blog-covers/kit.mjs';
import { sceneScore, sceneList, sceneCompare, scenePhone, sceneSerp, scenePrice, sceneSteps } from '../../lib/blog-covers/scenes.mjs';

/**
 * One cover per article: [glow colour, scene, what the scene shows].
 *
 * Every word and figure here comes from the article it illustrates — that is
 * what makes the picture ours rather than a stock photo. build.mjs refuses a
 * cover whose figures do not appear in its article.
 *
 * A new article gets a cover by adding an entry here and running
 * `node scripts/blog-covers/build.mjs`.
 */
export function covers(bySlug) {
  /** Sub-headings of one chapter, straight from the article, without numbering. */
  const h3 = (slug, chapter, n = 5) => {
    const sec = (bySlug[slug]?.content ?? '').split(/^##\s+/m).find((s) => s.split('\n')[0].toLowerCase().includes(chapter.toLowerCase())) ?? '';
    return [...sec.matchAll(/^###\s+(.+)$/gm)].map((m) => m[1].replace(/^\d+\.\s*/, '').replace(/[*_`]/g, '').replace(/\s*\(.*?\)\s*$/, '').trim()).slice(0, n);
  };
  const A = C.amberL, T = C.tealL;

  return {
  'jak-jsme-zrychlili-web-pagespeed-pripadova-studie': ['#6366f1', sceneScore, { domain: 'weblyx.cz', cookie: true, tag: 'LCP', bars: { title: 'NAČTENÍ', rows: [{ w: 250, s: '7,2 s', amber: true }, { w: 84, s: '2,4 s' }] }, pct: 98, big: '98', label: 'PageSpeed', mini: { ring: 64, big: '64' } }],
  'proc-vas-web-nikdo-nenavstevuje': ['#f43f5e', sceneList, { domain: 'vasefirma.cz', heading: ['Proč váš web', 'nikdo nenavštěvuje'], mark: 'warn', hl: 0, rows: ['Je neviditelný pro Google', 'Načítá se jako v roce 2005', 'Není důvod se vracet', 'Nikdo neví, že existuje', 'Neřeší problém zákazníka'], stat: { big: '5', label: ['brutálně upřímných', 'důvodů'] }, mini: { big: '12 návštěv', label: 'za měsíc', amber: true } }],
  'jak-vybrat-domenu-pro-web': ['#3b82f6', sceneList, { domain: 'kadernictvi-krasa.cz', heading: ['Jak vybrat doménu'], rows: h3('jak-vybrat-domenu-pro-web', '7 pravidel'), hl: 0, stat: { big: '7', label: ['pravidel pro výběr', 'domény'] }, pills: ['.cz', '.com', '.eu', '.sk'], mini: { big: '.cz', label: 'pro 90 % firem' } }],
  'jak-ziskat-vice-zakazniku-online': ['#8b5cf6', sceneList, { domain: 'vasefirma.cz', heading: ['Jak získat více', 'zákazníků online'], rows: ['SEO', 'Google Ads (PPC reklama)', 'Google Business Profile', 'Sociální sítě', 'Meta Ads'], stat: { big: '10', label: ['strategií,', 'které fungují'] }, pills: ['Email marketing', 'Obsahový marketing'] }],
  'co-je-seo-zaklady-optimalizace': ['#3b82f6', sceneSerp, { domain: 'google.com', query: 'instalatérství Praha 6', results: ['Instalatérství Praha 6 | Nonstop opravy', 'Úvod', 'Úvod'], stat: { big: '3', label: ['pilíře SEO'] }, pills: ['Title tag', 'Meta description', 'H1 nadpis', 'Obsah'], mini: { big: 'SEO', label: 'vs. PPC' } }],
  'kdy-predelat-web-redesign': ['#f59e0b', sceneList, { domain: 'vasefirma.cz', heading: ['Je čas na redesign?'], mark: 'warn', rows: ['Web je pomalý', 'Nefunguje na mobilu', 'Design vypadá zastarale', 'Web nepřivádí zákazníky', 'Nemůžete web sami upravovat'], stat: { big: '7', label: ['signálů, že je čas', 'na redesign'] } }],
  'jak-psat-texty-na-web-copywriting': ['#ec4899', sceneList, { domain: 'vasefirma.cz', heading: ['Texty, které prodávají'], hl: 2, rows: ['Mluvte o zákazníkovi, ne o sobě', 'Řešte problém, ne funkce', 'Nadpis je 80 % úspěchu', 'Jeden odstavec = jedna myšlenka', 'Používejte čísla a konkrétní údaje'], stat: { big: '10', label: ['pravidel', 'copywritingu'] }, mini: { big: '80 %', label: 'dělá nadpis' } }],
  'email-marketing-male-firmy-2026': ['#6366f1', scenePhone, { domain: 'vasefirma.cz', screen: 'mail', data: { title: 'Doručené', rows: ['Uvítací série', 'Newsletter', 'Prodejní emaily', 'Transakční emaily'] }, stats: [{ big: '4 200 %', label: ['ROI email', 'marketingu'] }, { big: '99 %', label: ['kontroluje email', 'každý den'] }], pills: ['Nástroj', 'Sběr emailů', 'Automatizace', 'Měření'] }],
  'gdpr-webove-stranky-2026': ['#3b82f6', scenePhone, { domain: 'vasefirma.cz', screen: 'cookie', data: { title: 'Cookies', yes: 'Přijmout', no: 'Odmítnout' }, stats: [{ big: 'GDPR', label: ['co musí web splnit', 'v roce 2026'] }, { big: '6', label: ['nejčastějších', 'chyb na webech'] }], pills: ['Cookie lišta', 'Formuláře', 'Newsletter', 'Zásady ochrany údajů', 'Google Analytics'] }],
  'google-firemni-profil-navod': ['#f59e0b', scenePhone, { domain: 'google.com', screen: 'profile', data: { name: 'Vaše firma', rating: 'recenze', actions: ['Volat', 'Trasa', 'Web'] }, stats: [{ big: '7×', label: ['více kliknutí', 's vyplněným profilem'] }, { big: '6', label: ['kroků od registrace', 'po měření'] }], pills: ['Google Mapy', 'Map Pack', 'Fotografie', 'Recenze', 'Google Posts'] }],
  'jak-pripravit-podklady-pro-novy-web': ['#8b5cf6', sceneList, { domain: 'weblyx.cz', heading: ['Podklady pro nový web'], mark: 'check', rows: ['Logo (ideálně SVG/AI)', 'Texty pro hlavní stránky', 'Kontaktní údaje', 'Minimálně 5 fotografií', 'Přístupy k doméně a hostingu'], stat: { big: '6', label: ['oblastí, které', 'si připravit'] }, pills: ['Barevná paleta', '3–5 webů jako inspirace', 'Reference'] }],
  'co-je-landing-page-kdy-potrebujete': ['#6366f1', sceneCompare, { left: { domain: 'web', neutral: true, title: 'Web', sub: 'Prezentace firmy', rows: ['5–20+ stránek', 'Plné menu', 'Informace, více akcí', 'Konverzní poměr 2–3 %'] }, right: { domain: 'landing page', title: 'Landing page', sub: 'Kampaně, akce', rows: ['1 stránka', 'Žádná / minimální navigace', 'Jedna konkrétní akce', 'Konverzní poměr 5–12 %'], foot: 'Od 7 990 Kč' } }],
  'facebook-vs-vlastni-web': ['#3b82f6', sceneCompare, { left: { domain: 'facebook.com', title: 'Facebook stránka', sub: 'Dosah: 2 % sledujících', rows: ['SEO minimální', 'Důvěryhodnost nízká', 'Kontrola žádná', 'Data vlastní Meta'], foot: 'Zdarma' }, right: { domain: 'vasefirma.cz', title: 'Vlastní web', sub: 'Dosah: neomezený (SEO)', rows: ['SEO plné', 'Důvěryhodnost vysoká', 'Kontrola plná', 'Data vlastníte vy'], foot: 'Od 7 990 Kč' } }],
  'lokalni-seo-male-firmy': ['#10b981', scenePhone, { domain: 'google.com', screen: 'map', data: { name: 'Vaše firma', rating: 'Map Pack' }, stats: [{ big: '46 %', label: ['vyhledávání má', 'lokální záměr'] }, { big: '78 %', label: ['vede k nákupu', 'do 24 hodin'] }], pills: ['Google Business Profile', 'Recenze', 'Lokální klíčová slova', 'NAP konzistence'] }],
  'nejcastejsi-chyby-tvorba-webu': ['#f43f5e', sceneList, { domain: 'vasefirma.cz', heading: ['Chyby, které stojí', 'zákazníky'], mark: 'cross', rows: ['Pomalé načítání', 'Žádné CTA (výzva k akci)', 'Není responzivní', 'Generické stockové fotky', 'Chybí SSL certifikát'], stat: { big: '10', label: ['nejčastějších chyb', 'firemních webů'] } }],
  'jak-zalozit-eshop-2026': ['#8b5cf6', scenePhone, { domain: 'vas-eshop.cz', screen: 'shop', data: { price: 'První objednávka', cta: 'Do košíku' }, stats: [{ big: '5', label: ['kroků od platformy', 'po první zákazníky'] }, { big: '15 000 Kč', label: ['až 60 000 Kč', 'na rozjezd'] }], pills: ['Platforma', 'Právní povinnosti', 'Fotografie', 'Platební brána a doprava', 'Marketing'] }],
  'ai-tvorba-webu-2026': ['#8b5cf6', sceneCompare, { vs: '+', left: { domain: 'AI', good: true, title: 'Co AI umí', sub: 'v roce 2026', rows: ['První návrhy textů', 'Přepis a zkrácení textů', 'SEO optimalizace', 'Blog na obecná témata'] }, right: { domain: 'člověk', title: 'Co AI nenahradí', sub: 'Revoluce, nebo hype?', rows: ['Strategii', 'UX design', 'Branding', 'Technickou kvalitu'] } }],
  'kolik-stoji-udrzba-webu-rocne': ['#10b981', scenePrice, { domain: 'vasefirma.cz', heading: ['Roční provoz webu'], rows: [{ s: 'Doména', v: '200 Kč' }, { s: 'Hosting', v: '0–2 000 Kč' }, { s: 'SSL', v: '0 Kč' }, { s: 'Email (1 uživatel)', v: '1 500 Kč' }, { s: 'Drobné úpravy', v: '3 000 Kč' }], stat: { big: '4 700 Kč', label: ['až 6 700 Kč ročně', 'typický firemní web'] }, mini: { big: '200 Kč', label: 'minimum za rok' } }],
  'wordpress-vs-wix-vs-web-na-miru-2026': ['#3b82f6', sceneCompare, { left: { domain: 'WordPress · Wix', title: 'WordPress a Wix', sub: 'Náklady za 5 let', rows: ['WordPress 52 000 Kč', 'Wix 48 000 Kč', 'WordPress: PageSpeed 40–70', 'Měsíční náklady'], foot: 'Od 48 000 Kč' }, right: { domain: 'web na míru', title: 'Web na míru', sub: 'Next.js', rows: ['Měsíční náklady 0 Kč', 'PageSpeed 90–100/100', 'SEO výborné', 'Flexibilita maximální'], foot: '5× levnější za 5 let' } }],
  'jak-ziskat-recenze-od-zakazniku': ['#f59e0b', scenePhone, { domain: 'google.com', screen: 'reviews', data: { title: 'Recenze', rating: '4,5+' }, stats: [{ big: '93 %', label: ['lidí čte recenze', 'před nákupem'] }, { big: '20', label: ['recenzí jako cíl,', 'průměr 4,5+'] }], pills: ['Kde sbírat recenze', 'Jak odpovídat', 'Recenze na webu'] }],
  'webove-stranky-pro-zivnostniky-male-firmy': ['#10b981', sceneList, { domain: 'vasefirma.cz', heading: ['Web pro živnostníka'], mark: 'check', rows: h3('webove-stranky-pro-zivnostniky-male-firmy', 'Které stránky'), stat: { big: '2026', label: ['co musí web mít'] }, pills: ['Typické chyby', 'Kolik to stojí', '3 kroky'], mini: { big: '7 990 Kč', label: 'základní prezentace' } }],
  'web-zdarma-vs-profesionalni-web': ['#f43f5e', sceneCompare, { left: { domain: 'web zdarma', title: '„Web zdarma“', sub: 'Náklady za 5 let', rows: ['Wix Business 28 740 Kč', 'Webnode Standard 14 940 Kč', 'Vlastnictví: ne', 'Wix: PageSpeed 50–75'], foot: 'Prodraží se' }, right: { domain: 'vasefirma.cz', title: 'Web na míru', sub: 'Porovnání na 5 let', rows: ['Vlastnictví: ano', 'PageSpeed 90–100', 'SEO výborné', 'Nejrychlejší varianta'], foot: 'Nejlevnější varianta' } }],
  'jak-si-nechat-udelat-web-2026': ['#6366f1', sceneSteps, { steps: [{ tag: 'Den 1', title: 'Konzultace', sub: 'Potřeby, cíle, rozpočet', big: '1' }, { tag: 'Den 2–3', title: 'Návrh designu', sub: 'Ke schválení', big: '2' }, { tag: 'Den 3–7', title: 'Vývoj', sub: 'Obsah, SEO, analytika', big: '3' }], pct: 100, big: '7', label: 'DEN SPUŠTĚNÍ', pills: ['Výběr agentury', 'Na co se ptát', 'Co si připravit', 'Nejčastější chyby'] }],
  'kolik-stoji-webove-stranky-2026': ['#10b981', scenePrice, { domain: 'weblyx.cz/cenik-webu', heading: ['Kolik stojí web v roce 2026'], rows: [{ s: 'Landing page', v: 'od 7 990 Kč' }, { s: 'Firemní web (3–5 stránek)' }, { s: 'Rozšířený web (10+ stránek)' }, { s: 'E-shop', v: 'od 50 000 Kč' }], stat: { big: '7 990 Kč', pill: 'Reálné ceny od', label: ['agentury, freelanceři', 'i stavebnice'] }, pills: ['Co ovlivňuje cenu', 'Skryté náklady', 'Kde nešetřit'] }],
  'tvorba-webu-praha-jak-vybrat-agenturu-ceny': ['#3b82f6', sceneList, { domain: 'weblyx.cz', heading: ['5 otázek pro každou', 'agenturu'], rows: ['Jaký PageSpeed budou mít stránky?', 'Co všechno je v ceně?', 'Kdy bude web hotový?', 'Budu vlastnit zdrojový kód?', 'Můžete ukázat podobný projekt?'], stat: { big: 'Praha', label: ['300–400 agentur', 'a freelancerů'] } }],
  'ai-vyhledavani-nahrazuje-google-geo-optimalizace': ['#8b5cf6', scenePhone, { domain: 'ai-asistent', screen: 'chat', data: { q: 'Doporuč mi firmu v okolí', a: 'Odpověď AI', sources: ['zdroj', 'zdroj', 'zdroj'] }, stats: [{ big: '37 %', label: ['spotřebitelů hledá', 'přes AI'] }, { big: '93 %', label: ['odpovědí je', 'bez kliknutí'] }], pills: ['GEO optimalizace', '5 klíčových kroků'] }],
  'klient-chtel-web-za-5000-rekli-jsme-ne': ['#f43f5e', scenePrice, { domain: 'levny-web.cz', heading: ['Web za 5 000 Kč?'], rows: [{ s: 'Žádný návrh', bad: 1 }, { s: 'Žádná optimalizace rychlosti', bad: 1 }, { s: 'Žádné SEO', bad: 1 }, { s: 'Žádná responzivita na míru', bad: 1 }, { s: 'Žádná strategie', bad: 1 }], stat: { big: '5 000 Kč', amber: true, pill: 'Řekli jsme ne', label: ['nebude to web,', 'bude to problém'] }, mini: { big: '30–50', label: 'PageSpeed šablony', amber: true } }],
  'postavili-jsme-web-za-3-dny-hodinu-po-hodine': ['#6366f1', sceneSteps, { steps: [{ tag: 'Den 1', title: 'Pondělí', sub: 'Plánování a design', big: '8 hodin' }, { tag: 'Den 2', title: 'Úterý', sub: 'Vývoj a obsah', big: '10 hodin' }, { tag: 'Den 3', title: 'Středa', sub: 'Testing, deploy, launch', big: '6 hodin' }], pct: 96, big: '96', label: 'PageSpeed', pills: ['24 hodin práce', '5 stránek', '7 990 Kč', 'Next.js'] }],
  'analyzovali-jsme-50-ceskych-webu-prumerny-pagespeed-43': ['#f59e0b', sceneScore, { domain: 'pagespeed.web.dev', pct: 43, big: '43', label: 'Průměr ze 100', amber: true, mini: { big: '50', label: 'českých webů' }, note: [{ s: '62 % webů pod 50', fill: A }, { s: 'jen 4 % nad 90', size: 20, fill: T }] }],
  'predrazene-sablony-webovych-agentur-jak-je-poznat': ['#f43f5e', sceneList, { domain: 'vasefirma.cz', heading: ['7 znaků předražené', 'šablony'], mark: 'warn', rows: h3('predrazene-sablony-webovych-agentur-jak-je-poznat', '7 znaků'), stat: { big: '90 %', label: ['agentur prodává', 'předražené šablony'] }, mini: { big: '40 000 Kč', label: 'vs. 49 dolarů', amber: true } }],
  '5-veci-co-si-opravite-sami-za-30-minut': ['#10b981', sceneList, { domain: 'vasefirma.cz', heading: ['5 oprav webu za 30 minut'], mark: 'check', rows: ['Optimalizuj obrázky', 'Oprav meta titulky a popisky', 'Přidej alt texty k obrázkům', 'Najdi a oprav rozbité odkazy', 'Odstraň zbytečné skripty'], stat: { big: '30', pill: 'Bez programátora', label: ['minut práce'] } }],
  'kolik-realne-vydelame-na-webu-za-8-tisic': ['#10b981', scenePrice, { domain: 'weblyx.cz', heading: ['Web za 8 000 Kč v číslech'], rows: [{ s: 'Úvodní hovor', v: '30 minut' }, { s: 'Design a návrh', v: '3–4 hodiny' }, { s: 'Celkem práce', v: '18 hodin' }, { s: 'Hodinová sazba', v: '444 Kč' }], stat: { big: '444 Kč', pill: '8 000 Kč ÷ 18 hodin', label: ['za hodinu práce'] } }],
  };
}
